# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ribbon',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name=b'my comments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='key',
            field=models.CharField(blank=True, help_text=b'Deprecated', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
